### ISSUE TITLE
请教测试结果如何重建为3d 图像？

### ISSUE THREAD

**Issue by wansongtai** [tommy-qichang/AsynDGAN#1]
test后的结果包含realA  realB  fakeB  分别是什么含义？  如何重建为3维图像呢？

**Comment by tommy-qichang** [comment]
realA: input mask which contains tumor mask and the brain skull.
realB: the real brain CT image.
fakeB: the synthetic brain CT image.

In this work, we just focus on 2D medical image, so there is no way to reconstruct 3D medical volume.
