### ISSUE TITLE
Segmentation process

### ISSUE THREAD

**Issue by nikku1234** [tommy-qichang/AsynDGAN#10]
Can you please explain how the segmentation process is done? I have generated the synthetic images using AsynDGAN, but I cannot find any code or explanation for the segmentation task.

**Comment by tommy-qichang** [comment]
Hi there,

The segmentation task as described in the paper, use vanila 2D U-Net network without any data augmentation.  You can use any segmentation methods just make sure it's fare comparasion between real and synthetic image. 
Also please note the 2D slices with tumor areas smaller than 10 pixels are excluded for both GAN training and segmentation phases for this paper.

**Comment by nikku1234** [comment]
Thanks for the fast reply, is there any reference code for the implementation?

**Comment by tommy-qichang** [comment]
Sorry for my late response. 
I'm willing to share my segmentation code in the near future. But right now, I need sometime to clean the codebase. (Because I have a lot of exp configurations all in one repository). 
But basically, it's the typical implementation of the 2D U-Net segmentation task.

Qi

**Comment by nikku1234** [comment]
Oh awesome, thanks!
