### ISSUE TITLE
Some questions about practical applications

### ISSUE THREAD

**Issue by Lyan-ing** [tommy-qichang/AsynDGAN#14]
In your paper, you train a generator that could map the mask to a real-like images, and use these generated images as training samples. You treat the label in datasets as mask and input the model (i'm not sure if my understand is correct), however, how the local entities get label as mask? I mean, how can we get the input of generator if we want to generate large number of images? Does random generate mask as input  is make sense?

**Comment by tommy-qichang** [comment]
AsynDGAN only have one generator, which located in the center, so the masks do not need to share to the local entities. We use Pix2Pix as the backbone which is a conditional GAN, so we need the label as the mask. I think an unconditional gan generate random mask would also a interesting future work.

**Comment by Lyan-ing** [comment]
thank you for your reply!  how can we get the input of conditional generator if we want to generate large number of images? only use the label as mask? or could we craft new masks by appliy morphological operations (dilation and erosion) on original MASK ?

**Comment by tommy-qichang** [comment]
Yes, you can modify the masks by applying morphological operations. Also, in some case you could do  more. For instance, the masks contain skull and tumor, in such case, you can randomly merge different skull with the same tumor. Even though some of the combinations may not reasonable from the clinical point of view, but it may help the model to train better.

**Comment by tommy-qichang** [comment]
Also, by evaluate multiple times with the same mask could also generate different images given random noise. But so far from what I've tested, many data augmentation methods may not helpful to improve the final performance.

**Comment by Lyan-ing** [comment]
OK, thank you!

**Comment by tommy-qichang** [comment]
Feel free to open new tickets if you encounter any other issues.
