### ISSUE TITLE
data

### ISSUE THREAD

**Issue by junsuyiji** [tommy-qichang/AsynDGAN#15]
你好，我没有办法获取数据集，您能分享一下吗？

**Comment by tommy-qichang** [comment]
Could you please advise which dataset you need? BraTS or Nuclei?

**Comment by junsuyiji** [comment]
感谢您，我需要BraTS，祝您生活愉快，事业有成



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 25, 2022 22:13 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tommy-qichang/AsynDGAN] data (Issue #15)




 
Could you please advise which dataset you need? BraTS or Nuclei?

**Comment by tommy-qichang** [comment]
You can register from the official BraTS website. 
https://www.med.upenn.edu/sbia/brats2018/registration.html

Other useful link is here:
https://academictorrents.com/
