### ISSUE TITLE
How to build this work amongs differents institutions?  

### ISSUE THREAD

**Issue by BaochangZhang** [tommy-qichang/AsynDGAN#3]
it seems your work belong to distributed learning. is that so？ it is very interesting. so, how to build this work amongs differents institutions?  can you give me some tips?

**Comment by tommy-qichang** [comment]
Our work is inspired by Federated Learning, but apply distributed GAN architecture over various institutions. 
You could deploy several discriminators model over institutions while has a central generator synthetic images and distribute to different institutions.
