### ISSUE TITLE
Could you give me a training process? Thank you

### ISSUE THREAD

**Issue by shikangouyang** [tommy-qichang/AsynDGAN#4]
Could you give me a training process? Thank you

**Comment by tommy-qichang** [comment]
Basically the AsynDGAN training process is similar to the typical process of any other GAN.
After you clean your data, and start the training. 
The training script is here: `scripts/train_pix2pix.sh`
For more options, you can refer to the pix2pix repository: `https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/`

**Comment by shikangouyang** [comment]
Thank you,I already found out. Now looking at the code.thank you for your reply.

**Comment by shikangouyang** [comment]
Can you give me the data format of BRATS2018 divided into 10 categories? I wanted to run your code, but unfortunately it failed. If I know the format of your processed data, I can test my own data.  Looking forward to your reply, thank you.
