### ISSUE TITLE
The data processing

### ISSUE THREAD

**Issue by shikangouyang** [tommy-qichang/AsynDGAN#5]
Can you give me the data format of BRATS2018 divided into 10 categories? I wanted to run your code, but unfortunately it failed. If I know the format of your processed data, I can test my own data. Looking forward to your reply, thank you.

**Comment by tommy-qichang** [comment]
Hi @shikangouyang ,
You could refer to the data/brats_dataset.py for each of the subset, and data/brats_split_dataset.py for combining all(10) subsets together. 
Each subset has a hdf5 file with format: BraTS18_tumor_size_{idx}.h5
The content in each h5 is as followed:
data stored in path: "train/{keys}/t2"
label stored in path "train/{keys}/seg"

For more details please refer to the enclosed building script.


[brats_dataset_build.py.txt](https://github.com/tommy-qichang/AsynDGAN/files/5703602/brats_dataset_build.py.txt)

**Comment by shikangouyang** [comment]
I did it，thank you。I have six subsets. Is netD set to 6?
![image](https://user-images.githubusercontent.com/30751271/102438643-a769e700-4057-11eb-8e7e-685869fd2609.png)

**Comment by tommy-qichang** [comment]
That's right.

**Comment by shikangouyang** [comment]
Is there anything else that needs to be modified? I see a lot of commented code in asyndgan_model.py.

**Comment by tommy-qichang** [comment]
Yes, the current version need to manually modify the discriminator number in asyndgan_model.py, and brats_split_dataset.py

**Comment by shikangouyang** [comment]
I am very interested in your work, thank you for your guidance. I will continue to work hard. thanks

**Comment by tommy-qichang** [comment]
Glad to hear that. Let me know if you have any other questions. Good luck.

Qi
