### ISSUE TITLE
Questions about test

### ISSUE THREAD

**Issue by shikangouyang** [tommy-qichang/AsynDGAN#6]
I have got the latest_net_G.pth, but I always get an error when testing. I used save_syn.py to test. Can you give me some tips?Looking forward to your reply。thanks

**Comment by tommy-qichang** [comment]
Please provide the error msg and the command?

**Comment by shikangouyang** [comment]
python save_syn.py --dataroot /home/OYSK/codes/AsynDGAN/test --name AtoB --model asyndgan --netG resnet_9blocks --direction AtoB --dataset_mode brats_split --results_dir results/test_asyndgan
![image](https://user-images.githubusercontent.com/30751271/103227144-a6468d00-4968-11eb-9686-38b2b1899d55.png)

python save_syn.py --dataroot /home/OYSK/codes/AsynDGAN/test_demo --name AtoB --model asyndgan --netG resnet_9blocks --direction AtoB --dataset_mode brats --results_dir results/test_asyndgan
![image](https://user-images.githubusercontent.com/30751271/103227200-bf4f3e00-4968-11eb-8c70-adab3a185921.png)

When testing, input a picture or label, and then generate another picture. I am weak, sorry. Hope you can give more guidance

**Comment by shikangouyang** [comment]
python save_syn.py --dataroot /home/OYSK/codes/AsynDGAN/test --name AtoB --model asyndgan --netG resnet_9blocks --direction AtoB --dataset_mode brats_split --results_dir results/test_asyndgan
----------------- End -------------------
build key:0
dataset [BratsDataset] was created
opt.netG:resnet_9blocks
initialize network with normal
model [AsyndganModel] was created
Namespace(aspect_ratio=1.0, batch_size=1, checkpoints_dir='./checkpoints', crop_size=256, dataroot='/home/OYSK/codes/AsynDGAN/test_demo', dataset_mode='brats', direction='AtoB', display_id=-1, display_winsize=256, epoch='latest', eval=False, gpu_ids=[0], init_gain=0.02, init_type='normal', input_nc=3, isTrain=False, load_iter=0, load_size=256, max_dataset_size=inf, model='asyndgan', n_layers_D=3, name='AtoB', ndf=64, netD='basic', netG='resnet_9blocks', ngf=64, no_dropout=False, no_flip=True, norm='batch', ntest=inf, num_test=inf, num_threads=0, output_nc=3, phase='test', preprocess='resize_and_crop', results_dir='results/test_asyndgan', serial_batches=True, suffix='', verbose=False)
loading the model from ./checkpoints/AtoB/latest_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.383 M
-----------------------------------------------
Traceback (most recent call last):
  File "save_syn.py", line 115, in <module>
    model.set_input(data)  # unpack data from data loader
  File "/home/OYSK/codes/AsynDGAN/models/asyndgan_model.py", line 116, in set_input
    self.real_A.append(input['A_' + str(i)].to(self.device))
KeyError: 'A_0'



When testing, input a picture or label, and then generate another picture. I am weak, sorry. Hope you can give more guidance

**Comment by shikangouyang** [comment]
python save_syn.py --dataroot /home/OYSK/codes/AsynDGAN/test_demo --name AtoB --model asyndgan --netG resnet_9blocks --direction AtoB --dataset_mode brats --results_dir results/test_asyndgan
----------------- End -------------------
build key:0
dataset [BratsDataset] was created
opt.netG:resnet_9blocks
initialize network with normal
model [AsyndganModel] was created
Namespace(aspect_ratio=1.0, batch_size=1, checkpoints_dir='./checkpoints', crop_size=256, dataroot='/home/OYSK/codes/AsynDGAN/test_demo', dataset_mode='brats', direction='AtoB', display_id=-1, display_winsize=256, epoch='latest', eval=False, gpu_ids=[0], init_gain=0.02, init_type='normal', input_nc=3, isTrain=False, load_iter=0, load_size=256, max_dataset_size=inf, model='asyndgan', n_layers_D=3, name='AtoB', ndf=64, netD='basic', netG='resnet_9blocks', ngf=64, no_dropout=False, no_flip=True, norm='batch', ntest=inf, num_test=inf, num_threads=0, output_nc=3, phase='test', preprocess='resize_and_crop', results_dir='results/test_asyndgan', serial_batches=True, suffix='', verbose=False)
loading the model from ./checkpoints/AtoB/latest_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.383 M
Traceback (most recent call last):
File "save_syn.py", line 115, in
model.set_input(data) # unpack data from data loader
File "/home/OYSK/codes/AsynDGAN/models/asyndgan_model.py", line 116, in set_input
self.real_A.append(input['A_' + str(i)].to(self.device))
KeyError: 'A_0'

python save_syn.py --dataroot /home/OYSK/codes/AsynDGAN/test --name AtoB --model asyndgan --netG resnet_9blocks --direction AtoB --dataset_mode brats_split --results_dir results/test_asyndgan
----------------- End -------------------
Load: BraTS18_tumor_size_0.h5
build key:0
Load: BraTS18_tumor_size_1.h5
build key:0
Load: BraTS18_tumor_size_2.h5
build key:0
dataset [BratsSplitDataset] was created
opt.netG:resnet_9blocks
initialize network with normal
model [AsyndganModel] was created
Namespace(aspect_ratio=1.0, batch_size=1, checkpoints_dir='./checkpoints', crop_size=256, dataroot='/home/OYSK/codes/AsynDGAN/test', dataset_mode='brats_split', direction='AtoB', display_id=-1, display_winsize=256, epoch='latest', eval=False, gpu_ids=[0], init_gain=0.02, init_type='normal', input_nc=3, isTrain=False, load_iter=0, load_size=256, max_dataset_size=inf, model='asyndgan', n_layers_D=3, name='AtoB', ndf=64, netD='basic', netG='resnet_9blocks', ngf=64, no_dropout=False, no_flip=True, norm='batch', ntest=inf, num_test=inf, num_threads=0, output_nc=3, phase='test', preprocess='resize_and_crop', results_dir='results/test_asyndgan', serial_batches=True, suffix='', verbose=False)
loading the model from ./checkpoints/AtoB/latest_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.383 M
-----------------------------------------------
Traceback (most recent call last):
  File "save_syn.py", line 119, in <module>
    gt = data['Seg']
KeyError: 'Seg'

When testing, input a picture or label, and then generate another picture. I am weak, sorry. Hope you can give more guidance

**Comment by tommy-qichang** [comment]
Sorry for my late response. But it seems when you evaluating, you should directly use the pix2pix model rather than use asyndgan model since the evaluation stage should just use the central generator.
